name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create report directory
        run: mkdir -p playwright-report
      - name: Run Playwright tests with report generation
        run: npx playwright test tests/simple-test.spec.ts --project=chromium --reporter=html,list
      - name: Create dummy report if tests fail
        if: failure()
        run: |
          mkdir -p playwright-report
          touch playwright-report/index.html
          echo '<html><body><h1>Test Run Failed</h1><p>Please check the logs for details.</p></body></html>' > playwright-report/index.html
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
